Controllers/StockEntryController.cs
using HospitalManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalManagementSystem.Controllers
{
    public class StockEntryController : Controller
    {
        private DateTime _SetDefaultDate = DateTime.Now;

        // GET: StockEntry
        public ActionResult ShowVendor()
        {
            if (Session["log"] != null)
            {
                LabCompanyContext vendorcontet = new LabCompanyContext();
                List<VendorModel> vendors = vendorcontet.vendordetails.ToList();
                return View(vendors);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Stock Entry " });
            }
        }
        public ActionResult AddVendor()
        {
            if (Session["log"] != null)
            {
                return View(new VendorDT());
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Vendor " });
            }
        }
        [HttpPost]
        public ActionResult AddVendor(VendorDT vendors)
        {
            if (Session["log"] != null)
            {

                using (var context = new HMSOnWebsEntities())
                {
                    using (var transaction = context.Database.BeginTransaction())
                    {
                        int MaxRefID = context.VendorDTs.Select(p => p.VID).DefaultIfEmpty(0).Max();
                        vendors.VID = MaxRefID + 1;
                        vendors.SyncSts = true;
                        vendors.HID = 1;
                        context.VendorDTs.Add(vendors);
                        context.SaveChanges();
                        transaction.Commit();
                        ModelState.Clear();
                        string message = "Vendor Created Successfully";
                        ViewBag.Message = message;
                        return View(new VendorDT());
                    }

                }
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Vendor " });
            }
        }

        [HttpGet]
        public ActionResult EditVendor(int id)
        {
            if (Session["log"] != null)
            {
                using (var context = new HMSOnWebsEntities())
                {
                    var data = context.VendorDTs.Where(x => x.VID == id).SingleOrDefault();
                    return View(data);
                }
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Vendor " });
            }
           
        }
        [HttpPost]
        public ActionResult EditVendor(int id,VendorDT vendors)
        {
            if (Session["log"] != null)
            {
                using (var context = new HMSOnWebsEntities())
                {
                    var data = context.VendorDTs.Where(x => x.VID == id).SingleOrDefault();
                    if(data!=null)
                    {
                        data.VendorName = vendors.VendorName;
                        data.GSTIN = vendors.GSTIN;
                        data.StateName = vendors.StateName;
                        data.StateCode = vendors.StateCode;
                        data.Address = vendors.Address;
                        data.Mobile = vendors.Mobile;
                        data.EmailId = vendors.EmailId;
                        data.OpBal = vendors.OpBal;
                        context.SaveChanges();
                        ModelState.Clear();
                        string message = "Vendor Modified Successfully";
                        ViewBag.Message = message;

                        // return RedirectToAction("ShowVendor");
                        // return PartialView(new VendorDT()); it returns same view

                         return View(new VendorDT());
                        //return PartialView("PartialViewExamples");
                    }
                    else
                    return View(data);
                }
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Vendor " });
            }

        }

        public ActionResult DeleteVendor()
        {
            using (var context = new HMSOnWebsEntities())
            {
                return View(new VendorDT());
            }
            
        }

        [HttpPost]
        public ActionResult DeleteVendor(int id)
        {
            using (var context = new HMSOnWebsEntities())
            {
                var data = context.VendorDTs.FirstOrDefault(x => x.VID == id);
                if (data != null)
                {
                    context.VendorDTs.Remove(data);
                    context.SaveChanges();
                    return RedirectToAction("ShowVendor");
                }
                else
                    return View();
            }

        }


        /*----------------------------------------*/
        public ActionResult ShowProducts()
        {
            if (Session["log"] != null)
            {
                LabCompanyContext dbcontext = new LabCompanyContext();
                List<LabItems> products = dbcontext.Products.ToList();
                return View(products);
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Stock Entry " });
            }
        }
        public ActionResult AddProducts()
        {
            if (Session["log"] != null)
            {
                return View(new LabItems());
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Stock Entry " });
            }
        }
        [HttpPost]
        public ActionResult AddProducts(LabItems models)
        {
            if (Session["log"] != null)
            {
                if (ModelState.IsValid)
                {
                    using (var context = new HMSOnWebsEntities())
                    {
                        using (var transaction = context.Database.BeginTransaction())
                        {


                            LabITEMDT lab = new LabITEMDT();
                            lab.ItemName = models.ItemName;
                            lab.OPQTY = models.OPQTY;
                            long MaxRefID = context.LabITEMDTs.Select(p => p.ITEMID).DefaultIfEmpty(0).Max();
                            lab.ITEMID = MaxRefID + 1;

                            lab.OnDate = _SetDefaultDate;
                            lab.Createdby = Session["log"].ToString();
                            lab.BrID = 1;
                            lab.HID = 1;
                            context.LabITEMDTs.Add(lab);
                            context.SaveChanges();
                            transaction.Commit();
                            ModelState.Clear();
                            string message = "Product Added Successfully";
                            ViewBag.Message = message;
                            return View(new LabItems());
                        }

                    }
                }
                else
                {
                    return View(new LabItems());
                }
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Stock Entry " });
            }
        }


        public ActionResult EditProducts(long id)
        {
            if (Session["log"] != null)
            {
                using (var context = new HMSOnWebsEntities())
                {
                    var data = context.LabITEMDTs.Where(x => x.ITEMID == id).SingleOrDefault();
                    return View(data);
                }
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Stock Entry " });
            }
        }
        [HttpPost]
        public ActionResult EditProducts(long id,LabITEMDT labitems)
        {
            if (Session["log"] != null)
            {
                using (var context = new HMSOnWebsEntities())
                {
                    var data = context.LabITEMDTs.Where(x => x.ITEMID == id).SingleOrDefault();
                    if (data != null)
                    {
                        data.ItemName = labitems.ItemName;
                        data.OPQTY = labitems.OPQTY;
                        labitems.OnDate = _SetDefaultDate;
                        labitems.Createdby = Session["log"].ToString();
                        labitems.BrID = 1;
                        labitems.HID = 1;
                        context.SaveChanges();
                        ModelState.Clear();
                        string message = "Product Modified Successfully";
                        ViewBag.Message = message;
                        return RedirectToAction("ShowProducts");

                    }
                    else
                        return View(new LabITEMDT());
                }
            }
            else
            {
                return RedirectToAction("Login", "Home", new { Redirected = "Redirected To Login From Stock Entry " });
            }
        }

       
        public ActionResult DeleteProducts()
        {
            using (var context = new HMSOnWebsEntities())
            {
                return View(new LabITEMDT());
            }

        }


        [HttpPost]

Views/StockEntry/AddProducts.cshtml
@model HospitalManagementSystem.Models.LabItems


@{
    ViewBag.Title = "ShowVendor";
    Layout = "~/Views/Shared/_MainPageLayout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Product List</title>
    <link href="~/Content/assets/css/bootstrap.min.css" rel="stylesheet" />
    @*<link href="~/Content/assets/mymodalcss.css" rel="stylesheet" />*@
    @*<style>
            .modal fade {
                display: none; /* Hidden by default */
                position: fixed; /* Stay in place */
                z-index: 1; /* Sit on top */
                left: 0;
                top: 0;
                width: 100%; /* Full width */
                height: 100%; /* Full height */
                overflow: auto; /* Enable scroll if needed */
                background-color: rgb(0,0,0); /* Fallback color */
                background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            }
        </style>*@
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

</head>
<body>

    <div class="page-body">
        <div class="container-fluid">
            <div class="page-body-wrapper">
                <div class="container-fluid">
                    <br />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="row">
                            <div class="col-md-2">
                                <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#AddModal">Open Add modal</a>
                            </div>
                            <div class="col-md-2">
                                @Html.ActionLink("Back to List", "ShowProducts", new object { }, new { @class = "btn btn-primary" })
                            </div>

                        </div>

                       


                        <div class="row">

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ItemName, "Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.OPQTY, "Opening Stock", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.OPQTY, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.OPQTY, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-primary" />
                                </div>
                            </div>
                            <div>
                                @Html.ActionLink("Back to List", "ShowProducts", new object { }, new { @class = "btn btn-info-gradien" })
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>

       

        <!------------script to add products using ajax-->
        @*<script>
                //const { data } = require("jquery");
                $(document).ready(function () {
                    $("btnsubmit").click(function () {
                        $("#loaderdiv").show();
                        var myformData = $("myForm").serialize();


                        $.ajax({
                            type: "POST",
                            url: "/StockEntry/AddProducts",
                            data: myformData,
                            success: function () {

                                $("#loaderdiv").hide();
                                $("#AddModal").modal('hide');
                                setInterval('location.reload()', 500);


                            }


                        }) // ajax function end



                    }) // Click function end

                })   // ready  function end



            </script>*@

        <script>

            var AddProduct = function () {
                $("#loaderdiv").show();
                var myformData = $("myForm").serialize();

                $.ajax({
                    type: "POST",
                    url: "/StockEntry/AddProducts",
                    data: myformData,
                    success: function () {

                        $("#loaderdiv").hide();
                        $("#AddModal").modal('hide');
                        setInterval('location.reload()', 500);
                    }
                })

            }
        </script>
    </body>
</html>

Views/StockEntry/AddProductsWithjquery.cshtml
@model HospitalManagementSystem.Models.LabItems

@{
    ViewBag.Title = "AddProductsWithjquery";
    Layout = "~/Views/Shared/_MainPageLayout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Product List</title>
    <link href="~/Content/assets/css/bootstrap.min.css" rel="stylesheet" />
    @*<link href="~/Content/assets/mymodalcss.css" rel="stylesheet" />*@
    @*<style>
            .modal fade {
                display: none; /* Hidden by default */
                position: fixed; /* Stay in place */
                z-index: 1; /* Sit on top */
                left: 0;
                top: 0;
                width: 100%; /* Full width */
                height: 100%; /* Full height */
                overflow: auto; /* Enable scroll if needed */
                background-color: rgb(0,0,0); /* Fallback color */
                background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            }
        </style>*@
</head>
<body>

    <div class="page-body">
        <div class="container-fluid">
            <div class="page-body-wrapper">
                <div class="container-fluid">
                    <h2>AddProductsWithjquery</h2>

                    @using (Html.BeginForm("AddProductsWithjquery", "StockEntry", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>LabItems</h4>
                            <div class="row">
                                <div class="col-md-2">
                                    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#AddModal">Open Add modal</a>
                                </div>
                                <div class="col-md-2">
                                    @Html.ActionLink("Back to List", "ShowProducts", new object { }, new { @class = "btn btn-primary" })
                                </div>

                            </div>

                           



                        </div>

                    }


                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/StockEntry/AddVendor.cshtml
@model HospitalManagementSystem.VendorDT

@{
    ViewBag.Title = "AddVendor";
    Layout = "~/Views/Shared/_MainPageLayout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Vendor List</title>
</head>
<body>
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-body-wrapper">
                <div class="container-fluid">
                    <br />
                    <div class="row">
                        <div class="col-md-2">
                            @Html.ActionLink("Vendor List", "ShowVendor", new object { }, new { @class = "btn btn-info-gradien" })
                        </div>
                        <div class="col-md-6">
                            <h4>@ViewBag.Message</h4>
                        </div>

                    </div>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="row">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.VendorName, "Vendor Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.VendorName, new { htmlAttributes = new { @class = "form-control", placeholder = "Vendor Name", @style = "text-transform:uppercase" } })
                                            @Html.ValidationMessageFor(model => model.VendorName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.GSTIN, "GST NO", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.GSTIN, new { htmlAttributes = new { @class = "form-control", placeholder = "GST No", @style = "text-transform:uppercase" } })
                                            @Html.ValidationMessageFor(model => model.GSTIN, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", placeholder = "Address " } })
                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.StateName, "State Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.StateName, new { htmlAttributes = new { @class = "form-control", placeholder = "State Name " } })
                                            @Html.ValidationMessageFor(model => model.StateName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.StateCode, "State Code", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.StateCode, new { htmlAttributes = new { @class = "form-control", placeholder = "State Code " } })
                                            @Html.ValidationMessageFor(model => model.StateCode, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control", placeholder = "Mobile No " } })
                                            @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>




                            <div class="row">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.EmailId, "Email ID", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Email ID " } })
                                            @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.OpBal, "Opening Balance", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.OpBal, new { htmlAttributes = new { @class = "form-control", placeholder = "Opening Balance " } })
                                            @Html.ValidationMessageFor(model => model.OpBal, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-outline-success-2x" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/StockEntry/DeleteProducts.cshtml
@model HospitalManagementSystem.LabITEMDT
@{
    ViewBag.Title = "ShowVendor";
    Layout = "~/Views/Shared/_MainPageLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Product </title>
</head>
<body>
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-body-wrapper">
                <div class="container-fluid">
                    <br />
                    <h3>Are you sure you want to delete this?</h3>
                    <div>

                        <hr />
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this record?');" /> |
                                @Html.ActionLink("Back to List", "ShowProducts")
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/StockEntry/DeleteVendor.cshtml
@model HospitalManagementSystem.VendorDT

@{
    ViewBag.Title = "ShowVendor";
    Layout = "~/Views/Shared/_MainPageLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete Vendor </title>
</head>
<body>

    <div class="page-body">
        <div class="container-fluid">
            <div class="page-body-wrapper">
                <div class="container-fluid">
                    <h3>Are you sure you want to delete this?</h3>
                    <div>

                        <hr />


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>


                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/StockEntry/Details.cshtml
@model HospitalManagementSystem.LabITEMDT

<table cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td valign="top"><b>@Html.DisplayNameFor(model => model.ITEMID):</b></td>
        <td>
            @Html.DisplayFor(model => model.ItemName)
            <br />
            @Html.DisplayFor(model => model.OPQTY),
        </td>
    </tr>
</table>

Views/StockEntry/EditProducts.cshtml
@model HospitalManagementSystem.LabITEMDT
@{
    ViewBag.Title = "ShowVendor";
    Layout = "~/Views/Shared/_MainPageLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Product </title>
</head>
<body>
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-body-wrapper">
                <div class="container-fluid">
                    <br />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ITEMID)


                            <div class="form-group">
                                @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.OPQTY, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.OPQTY, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.OPQTY, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save"  class="btn btn-outline-success-2x"/>
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "ShowProducts", new object { }, new { @class = "btn btn-info-gradien" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>